### ISSUE TITLE
Some thoughts on distribution

### ISSUE THREAD

**Issue by rpdelaney** [Omni-guides/Wabbajack-Linux-Bottles#3]
Thank you very much for providing this guide. Myself, I do not have a steam deck, but I use linux as a daily driver and I'm unwilling to install windows for games, despite the challenges. 

What you have written here leaves me wondering if it would be possible to distribute Wabbajack on linux as a flatpak itself. Have you looked into this possibility?

**Comment by Omni-guides** [comment]
Hello!

I have not considered that - mostly because WJ just flat out does not work via Wine at all any more. I do try again every so often to see if I can garner some more inspiration, but every time I clear one hurdle, another seemingly unfixable blocker appears at the next step of the WJ process. For now, I have had to resort to a minimal (25GB) Windows VM that has the sole purpose of running WJ.

I'd be delighted to be proven wrong and work with someone to get WJ up and running via Wine, but for now, I have reached the end of my abilities.

**Comment by rpdelaney** [comment]
Fair enough. It may be best to put a deprecation warning on the repo and archive it for the time being, in that case. That would save users struggling to follow the guide, not knowing it doesn't work anymore.

Related, are you still `@omni` on the discord? I couldn't find you there...

**Comment by Omni-guides** [comment]
Yeah, I suppose you are right. There was a time when you could still just about get by using the older version of WJ specifically mentioned at the start of the guide, but no doubt that is no longer viable.

I had retained some hope that I'd work out a method to get WJ running, but I can always recreate a guide if I ever get to that stage.

And yes, if you mean the official Wabbajack discord, I'm still there - you can find me in the #unofficial-linux-help channel.

**Comment by Omni-guides** [comment]
I added some flags around this repository to alert people that it is deprecated and no longer works.I'll leave it up in case it helps someone get further than I did, or if I make a breakthrough.
